//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStock
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int Id_prod { get; set; }
        public string Marque { get; set; }
        public string Nom_prod { get; set; }
        public string Adresse_Mac { get; set; }
        public int Id_util { get; set; }
        public int Id_Site { get; set; }
        public int Id_cat { get; set; }
    
        public virtual Categorie Categorie { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual Sites Sites { get; set; }
    }
}
